#ifndef OPCODES_H
#define OPCODES_H

#define OP_Goto                   1
#define OP_Gosub                  2
#define OP_Return                 3
#define OP_InitCoroutine          4
#define OP_EndCoroutine           5
#define OP_Yield                  6
#define OP_HaltIfNull             7
#define OP_Halt                   8
#define OP_Integer                9
#define OP_Int64                  10
#define OP_Real                   11
#define OP_String8                12
#define OP_String                 13
#define OP_BeginSubrtn            14
#define OP_Null                   15
#define OP_SoftNull               16
#define OP_Blob                   17
#define OP_Variable               18
#define OP_Move                   19
#define OP_Copy                   20
#define OP_SCopy                  21
#define OP_IntCopy                22
#define OP_FkCheck                23
#define OP_ResultRow              24
#define OP_Concat                 25
#define OP_Add                    26
#define OP_Subtract               27
#define OP_Multiply               28
#define OP_Divide                 29
#define OP_Remainder              30
#define OP_CollSeq                31
#define OP_BitAnd                 32
#define OP_BitOr                  33
#define OP_ShiftLeft              34
#define OP_ShiftRight             35
#define OP_AddImm                 36
#define OP_MustBeInt              37
#define OP_RealAffinity           38
#define OP_Cast                   39
#define OP_Eq                     40
#define OP_Ne                     41
#define OP_Lt                     42
#define OP_Le                     43
#define OP_Gt                     44
#define OP_Ge                     45
#define OP_ElseEq                 46
#define OP_Permutation            47
#define OP_Compare                48
#define OP_Jump                   49
#define OP_And                    50
#define OP_Or                     51
#define OP_IsTrue                 52
#define OP_Not                    53
#define OP_BitNot                 54
#define OP_Once                   55
#define OP_If                     56
#define OP_IfNot                  57
#define OP_IsNull                 58
#define OP_IsType                 59
#define OP_ZeroOrNull             60
#define OP_NotNull                61
#define OP_IfNullRow              62
#define OP_Offset                 63
#define OP_Column                 64
#define OP_TypeCheck              65
#define OP_Affinity               66
#define OP_MakeRecord             67
#define OP_Count                  68
#define OP_Savepoint              69
#define OP_AutoCommit             70
#define OP_Transaction            71
#define OP_ReadCookie             72
#define OP_SetCookie              73
#define OP_ReopenIdx              74
#define OP_OpenRead               75
#define OP_OpenWrite              76
#define OP_OpenDup                77
#define OP_OpenAutoindex          78
#define OP_OpenEphemeral          79
#define OP_SorterOpen             80
#define OP_SequenceTest           81
#define OP_OpenPseudo             82
#define OP_Close                  83
#define OP_ColumnsUsed            84
#define OP_SeekLT                 85
#define OP_SeekLE                 86
#define OP_SeekGE                 87
#define OP_SeekGT                 88
#define OP_SeekScan               89
#define OP_SeekHit                90
#define OP_IfNotOpen              91
#define OP_IfNoHope               92
#define OP_NoConflict             93
#define OP_NotFound               94
#define OP_Found                  95
#define OP_SeekRowid              96
#define OP_NotExists              97
#define OP_Sequence               98
#define OP_NewRowid               99
#define OP_Insert                 100
#define OP_RowCell                101
#define OP_Delete                 102
#define OP_ResetCount             103
#define OP_SorterCompare          104
#define OP_SorterData             105
#define OP_RowData                106
#define OP_Rowid                  107
#define OP_NullRow                108
#define OP_SeekEnd                109
#define OP_Last                   110
#define OP_IfSizeBetween          111
#define OP_SorterSort             112
#define OP_Sort                   113
#define OP_Rewind                 114
#define OP_IfEmpty                115
#define OP_SorterNext             116
#define OP_Prev                   117
#define OP_Next                   118
#define OP_IdxInsert              119
#define OP_SorterInsert           120
#define OP_IdxDelete              121
#define OP_DeferredSeek           122
#define OP_IdxRowid               123
#define OP_FinishSeek             124
#define OP_IdxLE                  125
#define OP_IdxGT                  126
#define OP_IdxLT                  127
#define OP_IdxGE                  128
#define OP_Destroy                129
#define OP_Clear                  130
#define OP_ResetSorter            131
#define OP_CreateBtree            132
#define OP_SqlExec                133
#define OP_ParseSchema            134
#define OP_LoadAnalysis           135
#define OP_DropTable              136
#define OP_DropIndex              137
#define OP_DropTrigger            138
#define OP_IntegrityCk            139
#define OP_IFindKey               140
#define OP_RowSetAdd              141
#define OP_RowSetRead             142
#define OP_RowSetTest             143
#define OP_Program                144
#define OP_Param                  145
#define OP_FkCounter              146
#define OP_FkIfZero               147
#define OP_MemMax                 148
#define OP_IfPos                  149
#define OP_OffsetLimit            150
#define OP_IfNotZero              151
#define OP_DecrJumpZero           152
#define OP_AggInverse             153
#define OP_AggStep                154
#define OP_AggStep1               155
#define OP_AggValue               156
#define OP_AggFinal               157
#define OP_Checkpoint             158
#define OP_JournalMode            159
#define OP_Vacuum                 160
#define OP_IncrVacuum             161
#define OP_Expire                 162
#define OP_CursorLock             163
#define OP_CursorUnlock           164
#define OP_TableLock              165
#define OP_VBegin                 166
#define OP_VCreate                167
#define OP_VDestroy               168
#define OP_VOpen                  169
#define OP_VCheck                 170
#define OP_VInitIn                171
#define OP_VFilter                172
#define OP_VColumn                173
#define OP_VNext                  174
#define OP_VRename                175
#define OP_VUpdate                176
#define OP_Pagecount              177
#define OP_MaxPgcnt               178
#define OP_PureFunc               179
#define OP_Function               180
#define OP_ClrSubtype             181
#define OP_GetSubtype             182
#define OP_SetSubtype             183
#define OP_FilterAdd              184
#define OP_Filter                 185
#define OP_Trace                  186
#define OP_Init                   187
#define OP_CursorHint             188
#define OP_Abortable              189
#define OP_ReleaseReg             190

#endif /* OPCODES_H */
